# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder "wisdom", "/apps/"
  # config.vm.provision "ansible" do |ansible|
  #   ansible.playbook = configure.yml
  # end
end
