# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anchoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anchoringexperiment',
            name='name',
            field=models.CharField(default='Anchoring Experiment', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anchoringexperiment',
            name='text',
            field=models.TextField(default='The text of the question'),
            preserve_default=False,
        ),
    ]
